
export default interface Search {
    date: Date;
    time: String; // "09:00" || "10:00" || "11:00" ...
    location: String; // "outside" || "inside" ...
    capacity: String; // "1" || "2" || "3" ...
}